#server:
#  port: 9091
#spring:
#  application:
#    name: USER-SERVICE
#
#  profiles:
#    active: dev
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/microservices
#    username: root
#    password: root
#
#  config:
#    import: optional:configserver:http://localhost:9094